### ISSUE TITLE
licensing for bexvar in stingray?

### ISSUE THREAD

**Issue by dhuppenkothen** [JohannesBuchner/bexvar#1]
We're currently adapting to implement bexvar in stingray (cf. [this issue](https://github.com/StingraySoftware/stingray/issues/582)), but we're currently running into licensing issues: bexvar is GPL-licensed, which clashes with our own licence and that of some of our dependencies. Is there some way we could possibly use some of the code in the repo without having to change our own licence? Or do we need to develop from scratch based on the paper?

**Comment by dhuppenkothen** [comment]
ping @JohannesBuchner: we have adapted bexvar to work in stingray (see [this PR](https://github.com/StingraySoftware/stingray/pull/664)), but we're a bit worried about the issue of licensing. Can you advise?

**Comment by JohannesBuchner** [comment]
OK, I will comment in the issue. Sorry I overlooked the earlier notification email.
